// Renders the article-facing markdown tables + experiment_summary.json from the processed CSVs.
// Consumes the deterministic CSVs produced by the operational processors (tasks 1.1–1.9).
// Degrades gracefully: any missing/empty CSV yields a headers-only table and zero-row totals.
// No Date.now() — generated_at/batch/run_index come from a representative manifest or 'UNKNOWN'.
import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { safeMain } from './lib/run';
import { P, ensureDir, relPosix } from './lib/paths';
import { readCsv } from './lib/csv';
import { loadManifests, representativeManifest } from './lib/manifest';

type Row = Record<string, string>;

function loadCsv(name: string): { rows: Row[]; present: boolean } {
  const abs = join(P.processed, name);
  const rows = readCsv(abs);
  // readCsv returns [] for both missing and headers-only; distinguish via existence isn't
  // needed for the tables, but the summary records presence as "rows>0 OR file exists".
  return { rows, present: rows.length > 0 };
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.length === 0 ? [] : [...rows].sort().map((r) => `| ${r.join(' | ')} |`);
  return [head, sep, ...body].join('\n');
}

function num(v: string | undefined): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

safeMain('build-article-tables', () => {
  const manifests = loadManifests();
  const rep = representativeManifest(manifests);
  const architectureType = rep?.architectureType || 'TOM';
  const batchId = rep?.experimentBatchId || 'UNKNOWN';
  const runIndex = rep?.runIndex || 'UNKNOWN';
  const generatedAt = rep?.generatedAt || 'UNKNOWN';

  const inventory = loadCsv('scenario_inventory.csv');
  const coverage = loadCsv('platform_coverage_matrix.csv');
  const outcomes = loadCsv('scenario_outcome_history.csv');
  const scenarioDur = loadCsv('scenario_durations.csv');
  const platformDur = loadCsv('platform_durations.csv');
  const api = loadCsv('api_isolated_results.csv');
  const visual = loadCsv('visual_comparison_results.csv');
  const perf = loadCsv('performance_summary.csv');
  const failures = loadCsv('failure_buckets.csv');
  const proxy = loadCsv('proxy_overhead_summary.csv');

  const sections: string[] = [];

  sections.push('# TOM Article Tables');
  sections.push('');
  sections.push(
    `architecture_type = **${architectureType}** · experiment_batch_id = \`${batchId}\` · run_index = \`${runIndex}\` · generated_at = \`${generatedAt}\``,
  );
  sections.push('');
  sections.push('Generated by `scripts/metrics/build-article-tables.ts` from `metrics/processed/*.csv`.');
  sections.push('');

  // 1. Tool coverage — executions per tool (from outcome history).
  {
    const byTool = new Map<string, { runs: number; pass: number; fail: number }>();
    for (const r of outcomes.rows) {
      const tool = r.tool_name || 'UNKNOWN';
      const e = byTool.get(tool) ?? { runs: 0, pass: 0, fail: 0 };
      e.runs += 1;
      const outcome = (r.outcome || r.status || '').toUpperCase();
      if (outcome === 'PASS') e.pass += 1;
      else if (outcome === 'FAIL') e.fail += 1;
      byTool.set(tool, e);
    }
    const rows = [...byTool.entries()].map(([tool, e]) => [
      tool,
      String(e.runs),
      String(e.pass),
      String(e.fail),
    ]);
    sections.push('## 1. Tool coverage');
    sections.push('');
    sections.push(table(['tool_name', 'executions', 'pass', 'fail'], rows));
    sections.push('');
  }

  // 2. Feature-to-tool coverage — distinct (feature, tool) executed pairs.
  {
    const pairs = new Map<string, Set<string>>();
    for (const r of outcomes.rows) {
      const feature = r.feature || 'UNKNOWN';
      const tool = r.tool_name || 'UNKNOWN';
      const s = pairs.get(feature) ?? new Set<string>();
      s.add(tool);
      pairs.set(feature, s);
    }
    const rows = [...pairs.entries()].map(([feature, tools]) => [
      feature,
      [...tools].sort().join(', '),
      String(tools.size),
    ]);
    sections.push('## 2. Feature-to-tool coverage');
    sections.push('');
    sections.push(table(['feature', 'tools', 'tool_count'], rows));
    sections.push('');
  }

  // 3. Scenario inventory summary — per feature_file aggregation.
  {
    const byFile = new Map<string, { scenarios: number; exampleRows: number; steps: number }>();
    for (const r of inventory.rows) {
      const file = r.feature_file || 'UNKNOWN';
      const e = byFile.get(file) ?? { scenarios: 0, exampleRows: 0, steps: 0 };
      e.scenarios += 1;
      e.exampleRows += num(r.example_rows);
      e.steps += num(r.step_count);
      byFile.set(file, e);
    }
    const rows = [...byFile.entries()].map(([file, e]) => [
      file,
      String(e.scenarios),
      String(e.exampleRows),
      String(e.steps),
    ]);
    sections.push('## 3. Scenario inventory summary');
    sections.push('');
    sections.push(table(['feature_file', 'scenarios', 'example_rows', 'total_steps'], rows));
    sections.push('');
    sections.push(`**Total scenarios:** ${inventory.rows.length}`);
    sections.push('');
  }

  // 4. Scenario duration by tool/platform — from platform_durations.csv.
  {
    const rows = platformDur.rows.map((r) => [
      r.tool_name || 'UNKNOWN',
      r.platform || 'UNKNOWN',
      r.viewport || 'UNKNOWN',
      r.runs || '0',
      r.scenarios || '0',
      r.avg_ms || '',
      r.p50_ms || '',
      r.p95_ms || '',
      r.p99_ms || '',
      r.failures || '0',
    ]);
    sections.push('## 4. Scenario duration by tool/platform');
    sections.push('');
    sections.push(
      table(
        ['tool_name', 'platform', 'viewport', 'runs', 'scenarios', 'avg_ms', 'p50_ms', 'p95_ms', 'p99_ms', 'failures'],
        rows,
      ),
    );
    sections.push('');
  }

  // 5. API result summary.
  {
    let pass = 0;
    let fail = 0;
    let totalRt = 0;
    let rtCount = 0;
    for (const r of api.rows) {
      const s = (r.status || '').toUpperCase();
      if (s === 'PASS') pass += 1;
      else if (s === 'FAIL') fail += 1;
      const rt = Number(r.response_time_ms);
      if (Number.isFinite(rt)) {
        totalRt += rt;
        rtCount += 1;
      }
    }
    const avgRt = rtCount > 0 ? (Math.round((totalRt / rtCount) * 100) / 100).toString() : '';
    sections.push('## 5. API result summary');
    sections.push('');
    sections.push(
      table(
        ['total_calls', 'pass', 'fail', 'avg_response_time_ms'],
        [[String(api.rows.length), String(pass), String(fail), avgRt]],
      ),
    );
    sections.push('');
  }

  // 6. Visual result summary.
  {
    let passed = 0;
    let failed = 0;
    for (const r of visual.rows) {
      const p = (r.passed || '').toLowerCase();
      if (p === 'true') passed += 1;
      else if (p === 'false') failed += 1;
    }
    sections.push('## 6. Visual result summary');
    sections.push('');
    sections.push(
      table(
        ['total_comparisons', 'passed', 'failed'],
        [[String(visual.rows.length), String(passed), String(failed)]],
      ),
    );
    sections.push('');
  }

  // 7. Performance result summary — one row per simulation.
  {
    const rows = perf.rows.map((r) => [
      r.simulation_name || 'UNKNOWN',
      r.request_count || '0',
      r.success_count || '0',
      r.failure_count || '0',
      r.mean_response_time_ms || '',
      r.p95_response_time_ms || '',
      r.duration_ms || '',
    ]);
    sections.push('## 7. Performance result summary');
    sections.push('');
    sections.push(
      table(
        ['simulation_name', 'request_count', 'success_count', 'failure_count', 'mean_response_time_ms', 'p95_response_time_ms', 'duration_ms'],
        rows,
      ),
    );
    sections.push('');
  }

  // 8. Failure bucket distribution.
  {
    const byBucket = new Map<string, number>();
    for (const r of failures.rows) {
      const bucket = r.failure_bucket || 'UNCLASSIFIED';
      byBucket.set(bucket, (byBucket.get(bucket) ?? 0) + 1);
    }
    const rows = [...byBucket.entries()].map(([bucket, count]) => [bucket, String(count)]);
    sections.push('## 8. Failure bucket distribution');
    sections.push('');
    sections.push(table(['failure_bucket', 'count'], rows));
    sections.push('');
    sections.push(`**Total failures:** ${failures.rows.length}`);
    sections.push('');
  }

  // 9. Proxy overhead summary — per action_id.
  {
    const rows = proxy.rows.map((r) => [
      r.tool_name || 'UNKNOWN',
      r.platform || 'UNKNOWN',
      r.action_id || 'UNKNOWN',
      r.count || '0',
      r.avg_proxy_overhead_ms || '',
      r.p50_proxy_overhead_ms || '',
      r.p95_proxy_overhead_ms || '',
      r.avg_grpc_latency_ms || '',
    ]);
    sections.push('## 9. Proxy overhead summary');
    sections.push('');
    sections.push(
      table(
        ['tool_name', 'platform', 'action_id', 'count', 'avg_proxy_overhead_ms', 'p50_proxy_overhead_ms', 'p95_proxy_overhead_ms', 'avg_grpc_latency_ms'],
        rows,
      ),
    );
    sections.push('');
  }

  // 10. Quality attribute summary pointer.
  sections.push('## 10. Quality attribute summary');
  sections.push('');
  sections.push('See [article_quality_attributes.md](./article_quality_attributes.md) for the architecture quality-attribute table.');
  sections.push('');

  ensureDir(P.summary);
  const mdOut = join(P.summary, 'article_tables.md');
  writeFileSync(mdOut, sections.join('\n'), 'utf8');
  console.log(`[build-article-tables] wrote ${relPosix(mdOut)}`);

  // experiment_summary.json
  let pass = 0;
  let fail = 0;
  for (const r of outcomes.rows) {
    const o = (r.outcome || r.status || '').toUpperCase();
    if (o === 'PASS') pass += 1;
    else if (o === 'FAIL') fail += 1;
  }
  const artifactNames = [
    'scenario_inventory.csv',
    'platform_coverage_matrix.csv',
    'scenario_outcome_history.csv',
    'scenario_durations.csv',
    'platform_durations.csv',
    'api_isolated_results.csv',
    'visual_comparison_results.csv',
    'performance_summary.csv',
    'failure_buckets.csv',
    'proxy_overhead_summary.csv',
  ];
  const artifacts: Record<string, { present: boolean; rows: number }> = {};
  for (const name of artifactNames) {
    const abs = join(P.processed, name);
    const rows = readCsv(abs);
    artifacts[name] = { present: existsSync(abs), rows: rows.length };
  }

  const summary = {
    architecture_type: architectureType,
    experiment_batch_id: batchId,
    run_index: runIndex,
    generated_at: generatedAt,
    totals: {
      scenarios: inventory.rows.length,
      executions: outcomes.rows.length,
      pass,
      fail,
    },
    artifacts,
  };
  const jsonOut = join(P.summary, 'experiment_summary.json');
  writeFileSync(jsonOut, JSON.stringify(summary, null, 2) + '\n', 'utf8');
  console.log(`[build-article-tables] wrote ${relPosix(jsonOut)}`);
});
